travis:
  secure:
    BINSTAR_TOKEN: goq+ETorRasPLN/veTUnwiAmXb7K4PJlXa1bdDKD5YayjFAp5VCf8K4rayrZ64JXB8t2bJSLAXVLMPioJBxRZvZR3ZUcXIBgifFd/71XSa87NnI7pcB6OMWO5bxRUf2gUHc4OdxM5nsW7WWb7J498wJnJ3zV/Ft0oHTotE6Ki4+UJHNiclkSkrvQb+pujq3/A0oqqec6EGmVMYsL2jq3D3L3zetoJJCDebWBBOuPD20VONcJL5H2Ws1/wiLl+wbbZzEoBtCY+9LWOIcnJk91P/d0Lr9Fq3bh6P7S69+MD4de3TRT5Whz3pZE+N+sfowEWZMbIqcYmUi4DFJ5v9awXL7m5dOd1KaMUURMGwLiivPE/fC8fQf1YV/pckfY3UFwjlBoNIR5lKOh5LsAYAm99A83W+amT6b8wsIv7Rp/pTrS5JGeU+HsXVgiyXY+Tr6/39647sIzfyywSMXLNnUIg8TySoZ+NC8x0VWl4Qk2gRs+tnbVr9U33FTeVmDGYaiis4KN4Rh5JtUHbkQp0WHPLgz+CRPaXJAQXTyk8ApCN4Z9W32NqGgWb/aFzQ5avheoaLKsZ8atn1tDcE73Spq7X8bdBNkDlikOe5H+aDyV8HABAMZEXOaCtovKy64YbkmDqyASL3BupQkZUlw+gi7LFknELTMh26zHMc98eO5KTr4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
