travis:
  secure:
    BINSTAR_TOKEN: RyBcKJHviZn7sDi5A0yUiRIYJa9ZEmEBITP5hG/FEcUALzsAsVdGlHAD4zSWL5USlRzs3mpWKDib5jw5tHHloGfapzm1DkytgqtOTneb0USujefnefmtxSL+KeKLK4yJV7DYYXclniZTtLPG9OhmFnMexcxYlp0KiHxTZ4X5kNfbAlFABme9HAbkTrKX5yEPN3wkwzXl04pmpdCHueYhGs36Qa0P+iUQf7RRjhOoNXamlRumjWfF/9aBPYgCglmE+b/wx4E0f1GwbLElZL4Irf+pVjmTSVM6ABVL8dmcxXRQhabW+LGbsCpuPzocSYlAEG2861bfzHPQFfvjZVtvzc+gtXJsgQndsqlwkII/Kpi+Zf8Nfnd4AIUY8yD2PkRxAvREE3/rqKL2MfBV7R23qoVAPyaE6XbK+DHazWfFho/pyIaUDeDaPjz9x/0yuAC8vLzuTcZyFiCz8HsM4AaZ7xaJNdANDEdYFX20CKXuiJLJirYevPKO6uohHVq2xzvNhFRKQkhKvL1qYyGQSBPNwDg4RFqVpe7/h5Aq4xd4mRzmyoZgfZNGUms3Imqj6PYVZj0rQ6q1OgiKNdFKOoN7iavtbLBv3tkOSnejZn8VJtYxOGqSji71mvg9YRPNcPDGK1/qAlZCCGNsT5MAqmqWMWJTgp4ugI1GnjOdcRCRrP8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
