travis:
  secure:
    BINSTAR_TOKEN: Srcm9LzjsRLL6RirzHzwOrFYoZwph1gy3LAW236e4KNzR8IYJUcefIrhjMczbgWeZ9L23wGTVwA2wAQwkM7mKkp9bsQdknSAq/fSxH9Wf0a3usFKICJhhZXJbwhwt3ex476PXpqA7kG6k2T/PFAX9njiNDZZWIaRXL2hBPQ6HCNHBXdH7H9dbt/SK+Jz9t1+8hw9RMfZr7XZDCk045s+ZDYcmVF+yko00GoVXeCvkNhV/Hq+FohTRRuNZ4GoD8UAlHS1iYwLHCHlnzBptVMC+GXNeKOYr1/p7Z6zlmpohzVFZEAsA0LnBpdcM9qiQ4kUpsELBu0V41f6cOodYfaIRQJ7xwsPqtL7ExfHpqtEqvss4XdVXFqucYDb6V3Es8+q+9Auv8RInqqyB6AqqW5t3mgiaQmgXnB9CA3vEFbq3OvlrTDiJzPly8EtN99zOUfaGBERcS5971PMM9IAVODTXHEQiKL6BfLuN8xF+o4THUZK2oNeIupu7r5LqDr3EiIX5zppiguxbLKIxUq3gyZ4ZFLwjlFmhN7NG8T6gDkLLi9PQq7RRF2d/q7Hl7krcMS4da+AZdsQjKmBBhAJbv1qC+DD1qljM6gwClNUCsguv+72MKpVeVZsxg426/DzFqbJEINrKmqzQkO5wdb3jubtVwjSXBNGk3FnhP5ka8nKXRs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
