travis:
  secure:
    BINSTAR_TOKEN: uIDKcZ09GIlt9N8Lu+wabqi9QfhWHlDbyp8duhqGlsO3H/v1Nutbuz5vCki1CeZpQCc4rpZsqCpFL3Nc3EPudO33fEtxS0q5PNUi06tbl7WsKwsyTIWpWSHC6PJfOpwcdzQUn1bAU4KsnW2JBo7F/P2yZExACLRefCMHmWToWp4f/4kOCr2MtyM8c8NB1l1ir4FITtGXuGrnEvRGFf4WBFbeDfjzlVSr51BFOy1lI6i3RqorESuBYjNtHM6HhM1hh4mb3A4VKQGT4qnGfxmKEbbLa4XyVNC5hcNS0BEQCfTPvAB6I4mqDiNCiZ+JSd/s08bSnD9kdfd/oha/2iRNdYH1M4pJcwG7s7M/tjqrKs2pNtUkC7Qk6bjrV14ve/QjXbQmcSPQA9T/wHGn4ErTmliV3oUkv1mXzgDTLthPNByYcYrUQGo4S/VeFf29K2JWrr06SR4x4GobC5GHjrhjkLYaBQ3TraBkmBmd/sUpPhPrv6aMsUit2GnQz8+NtKRQbLvhxMHuv8q0bnHdV3NV3zp35B6Z1OCGdVhwvQLwC2GA92JByViLx5MuL1ysHjA4kCzaVL78qRJ4kOiiCQoftq+tTXw/TTJjlq7KATYdUmNeSkkQ4sQ7jybldTH7IBvX1TreXaIR2TJHWifY4nup4qcveu3F4SO5ZzBb9bJZ32w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
